In [2]:
import numpy as np
np.set_printoptions(precision=4,suppress=True)

A = np.array([[0.0375, 0.4625, 0.4625, 0.0375], 
              [0.4625, 0.0375, 0.0375, 0.4625], 
              [0.8875, 0.0375, 0.0375, 0.0375], 
              [0.25, 0.25, 0.25, 0.25]])
A


array([[0.0375, 0.4625, 0.4625, 0.0375],
       [0.4625, 0.0375, 0.0375, 0.4625],
       [0.8875, 0.0375, 0.0375, 0.0375],
       [0.25  , 0.25  , 0.25  , 0.25  ]])

In [3]:
x = np.array([1,0,0,0])
x = x.dot(A)
x

array([0.0375, 0.4625, 0.4625, 0.0375])

In [4]:
for i in range(100):
    x = x.dot(A)
x

array([0.3676, 0.2303, 0.2303, 0.1719])

In [8]:
y = np.array([0,0,0,1])
for i in range(20):
    y = y.dot(A)
y

array([0.3679, 0.2301, 0.2301, 0.172 ])

In [7]:
np.allclose(x,y)

False